merge `silken-forest-466023-a2.Sadhika_1_central.employee_master` target
using `silken-forest-466023-a2.Sadhika_1_central.employee_daily` source
on target.empid = source.empid

WHEN MATCHED AND (
  TARGET.NAME != SOURCE.NAME OR
  TARGET.DEPARTMENT != SOURCE.DEPARTMENT OR
  TARGET.SALARY != SOURCE.SALARY OR
  TARGET.STATUS = SOURCE.STATUS
) THEN
UPDATE SET
TARGET.NAME = SOURCE.NAME,
TARGET.DEPARTMENT = SOURCE.DEPARTMENT,
TARGET.SALARY = SOURCE.SALARY,
TARGET.STATUS = SOURCE.STATUS

WHEN NOT MATCHED BY TARGET THEN
INSERT (EMPID,NAME,DEPARTMENT,SALARY,STATUS)
VALUES (SOURCE.EMPID, SOURCE.NAME, SOURCE.DEPARTMENT, SOURCE.SALARY, SOURCE.STATUS)

WHEN NOT MATCHED BY SOURCE THEN
UPDATE SET TARGET.STATUS = 'Inactive'
